// File generated by `flutterfire configure`.
// To generate this file again, run `flutterfire configure --project=<your_firebase_project>`.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Returns the [FirebaseOptions] for the current platform.
///
/// To generate this file again, run `flutterfire configure --project=<your_firebase_project>`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeK3AGtvCN03CsdrUqw19ErG4NfmRFxA0',
    appId: '1:273722472959:android:88d7b4ccdffef1f5648fca',
    messagingSenderId: '273722472959',
    projectId: 'learninge-35cc4',
    storageBucket: 'learninge-35cc4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADXhlkhYWTJEPHNRfbbPWyYw9yyoXyNYU',
    appId: '1:273722472959:ios:390eed2a671c5b14648fca',
    messagingSenderId: '273722472959',
    projectId: 'learninge-35cc4',
    storageBucket: 'learninge-35cc4.firebasestorage.app',
    iosBundleId: 'com.example.ungdunghoctienganh',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    databaseURL: 'YOUR_DATABASE_URL',
    iosBundleId: 'com.example.ungdunghoctienganh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    databaseURL: 'YOUR_DATABASE_URL',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClohk-1VSB-P5Fv8nmx025EDpodeieSEg',
    appId: '1:273722472959:web:5466ea15442c53ce648fca',
    messagingSenderId: '273722472959',
    projectId: 'learninge-35cc4',
    authDomain: 'learninge-35cc4.firebaseapp.com',
    storageBucket: 'learninge-35cc4.firebasestorage.app',
    measurementId: 'G-Q0FF7HELHL',
  );
}
